name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Define el tag de la imagen
    - name: Set Image Tag
      id: imagetag
      run: echo "::set-output name=tag::$(date +%s)"

    # Build the Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag alvarosg97/portfolio:${{ steps.imagetag.outputs.tag }}

    # Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    # Push the image to Docker Hub
    - name: Push the image
      run: docker push alvarosg97/portfolio:${{ steps.imagetag.outputs.tag }}
